services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:base64:jlH/R0LTB+L6KKkeEtb9q0v0V4UJbHrd1R9a8KwWnIA=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: testDB
      - key: DB_USERNAME
        value: YOUR_DATABASE_USER
      - key: DB_PASSWORD
        value: YOUR_DATABASE_PASSWORD
